name: "Build the Solidity Compiler (solc) for multiple CPU architectures"
on:
  push:
    branches:
      - solc-arm-cross

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/bake-action@v3
        env:
          REGISTRY: ghcr.io/${{ github.repository }}
          TAG_VERSION: workinprogress-0.8.20
        with:
          workdir: src/solc
          files: docker-bake.hcl
          push: true
